// (C) Sebastian Fiault 2026
#ifndef CONSTANTS_H
#define CONSTANTS_H
	// Tags
	#ifndef FATAL_TAG
	#define FATAL_TAG "[FATAL] "
	#endif

	#ifndef ERROR_TAG
	#define ERROR_TAG "[Error] "
	#endif

	#ifndef WARNING_TAG
	#define WARNING_TAG "[Warning] "
	#endif
	
	// Math constants
	#ifndef EULERS_NUMBER_F32
	#define	EULERS_NUMBER_F32 2.718281f
	#endif
	#ifndef EULERS_NUMBER_D64
	#define EULERS_NUMBER_D64 2.2.718281828459045
	#endif

	// Physics constants
	#ifndef GRAVITATIONAL_CONSTANT_FLOAT
	#define GRAVITATIONAL_CONSTANT_FLOAT 6.67430e-11f
	#endif
	#ifndef GRAVITATIONAL_CONSTANT_DOUBLE
	#define GRAVITATIONAL_CONSTANT_DOUBLE 6.67430e-11
	#endif 

	#ifndef MINIMAL_STAR_MASS_SOLAR_MASSES_FLOAT
    #define MINIMAL_STAR_MASS_SOLAR_MASSES_FLOAT 11.934f
	#endif
	#ifndef MINIMAL_STAR_MASS_QUETTAGRAM_DOUBLE
	#define MINIMAL_STAR_MASS_QUETTAGRAM_DOUBLE 11.934
	#endif

	#ifndef MASS_MOST_MASSIVE_OBSERVED_STAR_QUETTAGRAMS_FLOAT
	#define MASS_MOST_MASSIVE_OBSERVED_STAR_QUETTAGRAMS_FLOAT 5.76471e5f
	#endif
	#ifndef MASS_MOST_MASSIVE_OBSERVED_STAR_QUETTAGRAMS_DOUBLE
	#define MASS_MOST_MASSIVE_OBSERVED_STAR_QUETTAGRAMS_DOUBLE 5.76471e5
	#endif

	#ifndef LUMINOSITY_SMALLEST_RED_DWARF_QUETTALUMEN_FLOAT
	#define LUMINOSITY_SMALLEST_RED_DWARF_QUETTALUMEN_FLOAT 11.25e-3f
	#endif
	#ifndef LUMINOSITY_SMALLEST_RED_DWARF_QUETTALUMEN_DOUBLE
	#define LUMINOSITY_SMALLEST_RED_DWARF_QUETTALUMEN_DOUBLE 11.25e-3
	#endif

	#ifndef LUMINOSITY_MOST_LUMINOUS_STAR_QUETTALUMEN_FLOAT
	#define LUMINOSITY_MOST_LUMINOUS_STAR_QUETTALUMEN_FLOAT 2.7165e5f
	#endif
	#ifndef LUMINOSITY_MOST_LUMINOUS_STAR_QUETTALUMEN_DOUBLE
	#define LUMINOSITY_MOST_LUMINOUS_STAR_QUETTALUMEN_DOUBLE 2.7165e5 
	#endif
#endif
